### ISSUE TITLE
 svd did not converge

### ISSUE THREAD

**Issue by chalth** [wentaoyuan/deepgmr#7]
Hello, when i tried to train the model, i meet with this error. Do you konw how to deal with this?

Traceback (most recent call last):
  File "train.py", line 174, in <module>
    train_one_epoch(epoch, model, train_loader, writer, args.log_freq, args.plot_freq)
  File "train.py", line 41, in train_one_epoch
    loss, r_err, t_err, rmse = model(pts1, pts2, T_gt)
  File "/home/lthach/anaconda3/envs/mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lthach/deepgmr-master/model.py", line 177, in forward
    self.T_12 = gmm_register(self.pi1, self.mu1, self.mu2, self.sigma2)
  File "/home/lthach/deepgmr-master/model.py", line 46, in gmm_register
    U, _, V = torch.svd(Ms)
RuntimeError: svd_cuda: the updating process of SBDSDC did not converge (error: 2)

**Comment by Rancho86** [comment]
I meet the same error

**Comment by liu-zikang** [comment]
Have you already solved the question？I meet the same error too.
